x-common-variables: &common-variables
  CHAIN_ID: mainnet
  META_DATABASE_URL: postgres://postgres:password@metadata_db:5432/near_data
  SHARD_0_DATABASE_URL: postgres://postgres:password@shard_0_db:5432/near_data
  SHARD_1_DATABASE_URL: postgres://postgres:password@shard_1_db:5432/near_data
  SHARD_2_DATABASE_URL: postgres://postgres:password@shard_2_db:5432/near_data
  SHARD_3_DATABASE_URL: postgres://postgres:password@shard_3_db:5432/near_data
  SHARD_4_DATABASE_URL: postgres://postgres:password@shard_4_db:5432/near_data
  SHARD_5_DATABASE_URL: postgres://postgres:password@shard_5_db:5432/near_data
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
  OTEL_EXPORTER_JAEGER_AGENT_PORT: 6831
  OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  NEAR_RPC_URL: https://rpc.mainnet.near.org
  ARCHIVAL_NEAR_RPC_URL: https://archival-rpc.mainnet.near.org
  AWS_BUCKET_NAME: near-lake-data-mainnet

services:
  rpc-server:
    build:
      context: .
      dockerfile: rpc-server/Dockerfile
      args:
        features: "tracing-instrumentation,shadow_data_consistency"
        profile: "dev-release"
    environment:
      <<: *common-variables
      TX_BUCKET_NAME: near-tx-local
      STORAGE_EMULATOR_HOST: http://gcs_emulator:9023
      RUST_LOG: "read_rpc_server=debug,shadow_data_consistency=debug,info"
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - gcs_emulator
      - metadata_db
      - shard_0_db
      - shard_1_db
      - shard_2_db
      - shard_3_db
      - shard_4_db
      - shard_5_db
      - jaeger

  state-indexer:
    build:
      context: .
      dockerfile: state-indexer/Dockerfile
      args:
        features: "tracing-instrumentation"
        profile: "dev-release"
    environment:
      <<: *common-variables
      STATE_INDEXER_ID: state-indexer-local
      RUST_LOG: "info"
    command: [ "from-interruption" ]
    ports:
      - "8081:8081"
    depends_on:
      - metadata_db
      - shard_0_db
      - shard_1_db
      - shard_2_db
      - shard_3_db
      - shard_4_db
      - shard_5_db
      - jaeger
    restart: on-failure

  tx-indexer:
    build:
      context: .
      dockerfile: tx-indexer/Dockerfile
      args:
        features: "tracing-instrumentation"
        profile: "dev-release"
    environment:
      <<: *common-variables
      REDIS_URL: redis://redis:6379/
      TX_INDEXER_ID: tx-indexer-local
      TX_BUCKET_NAME: near-tx-local
      STORAGE_EMULATOR_HOST: http://gcs_emulator:9023
      RUST_LOG: "info"
    command: [ "from-interruption" ]
    ports:
      - "8082:8082"
    depends_on:
      - gcs_emulator
      - metadata_db
      - shard_0_db
      - shard_1_db
      - shard_2_db
      - shard_3_db
      - shard_4_db
      - shard_5_db
      - jaeger
    restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:1.37
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    restart: always

  gcs_emulator:
    image: oittaa/gcp-storage-emulator:latest
    restart: on-failure
    entrypoint: ["/bin/sh","-c"]
    command: ["gcp-storage-emulator create_bucket near-tx-local && gcp-storage-emulator start"]
    ports:
      - "9023:9023"
    environment:
      PORT: 9023

  metadata_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"

  shard_0_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"

  shard_1_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"

  shard_2_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  shard_3_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  shard_4_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  shard_5_db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: near_data
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
